### ISSUE TITLE
make neutral dome grey

### ISSUE THREAD

**Issue by itVictor** [redsunservers/VSH-Rewrite#133]
white is a bit hard to see on some maps and the white flash on your screen when you're near the edge makes it really difficult to see anything compared to the other dome colors

grey would be best option that still represents a neutral color

**Comment by FortyTwoFortyTwo** [comment]
This is actually not as easy as i thought.
Current color is `192 192 192 255` (RGBA), rendermode is set to `RENDER_TRANSCOLOR` so the start fade can happen, but lowering RGB color makes dome more transparent, rather than changing color to black (even when alpha option is a thing).

Changing color to pure white (255 255 255 255) would ended up to this, if your wondering if that would help much or not.
![20200122175010_1](https://user-images.githubusercontent.com/33488710/72920377-130cdc80-3d41-11ea-901e-3d8511c5c16b.jpg)
