### ISSUE TITLE
Pyrocar Buff Options

### ISSUE THREAD

**Issue by Waifers** [redsunservers/VSH-Rewrite#167]
So after some time, it has become very apparent that Pyrocar is objectively the worst boss to try and win with out of all the other bosses. From weird quirks such as being unable to get back up from the crevice in vsh_crevice even with the jump pads (as seen in redsun-chat on the discord and what causes that is uhhh ??????),
![unknown](https://user-images.githubusercontent.com/34947804/81494702-86931500-9270-11ea-977c-3304aaa976a6.png)
to classes with flame resistance items taking longer to kill, with extreme cases being that Zatochi/Targe Demoknights are capable of indefinitely tanking Pyrocar. His rage is decent with that sweet damage one shotting the poor spy who just wanted to play a normal game of vsh, but that is all he pretty much has going for him besides being able to occasionally catch people off-guard by going brrrrrrrr with the flamethrower and the float jump.

Pyrocar should receive atleast one of these buffs.
-A small flat damage buff for the flamethrower.
-Attribute 797 (Attacks pierces damage resistance effects and bonuses).
-Anything else, he needs help and he can't get up on his own.

**Comment by Alex-Turtle** [comment]
Here's the changes I got so far with the Pyrocar to mimic the Hale's gameplay of going in a fight, kill a guy, and get out.

-Faster movement speed (380 instead of 345)
-Doubled damage (Damage pierce included)
-Shorter Flamethrower range
-Afterburn duration reduced by 90%
-Better mobility with the M2 (You fly high faster and the cooldown is shorter)

What is left for me to do before completing the update is to scale the rage damage depanding from the height of the stomp

**Comment by FortyTwoFortyTwo** [comment]
Changes done in #168
