### ISSUE TITLE
merasmus boss concept.

### ISSUE THREAD

**Issue by forgedisaman** [redsunservers/VSH-Rewrite#26]
1) boss - merasmus

2) base class - sniper

3) health tbc,(800 per player is my current proposal)

4) right click charge ability - halloween rocket jump spell 

(after charging up to 50% merasmus gains 1 use of the spell capping at 2 being stored at any given time.)

5) rage(s) what rage merasmus uses is based on his current rage percentage

rage 1 50% to 100% bombinomicon - merasmus gains a rocket launcher that shoots rockets using the bombinomicon model the rocket launcher starts with a clip size of 10 that should do around 90 damage on hit.

rage 2 101% to 175% reverse shove - players near merasmus are pulled in towards him (sort of like a reverse airblast) range is to be confirmed but around 500 hammer units sounds alright to me considering how big some maps can get.

rage 3 176% to 200% Flares - merasmus raises his staff in the air and pushes all reds into the sky dealing 60 damage and igniting anyone within a 1000 hammer unit radius shooting them into the air at a high speed.

upon using any of the above rages all of merasmus's rage is consumed and any of his previous rage effects that would give him something are nullified (rocket launcher, reverse airblast etc, no stacking effects.)

6) his melee should simply be the freedom staff until i can find / create an actual model for merasmus's staff (unless that already exsits somewhere.)

7) the general idea of this boss is to give rage and super jump as an expendable resource for the boss to use to their advantage, requiring a more strategical approach.

- so, any thoughts on about this boss design? anything at all is appreciated, thank you for your time.

**Comment by FortyTwoFortyTwo** [comment]
I did said before how rage mechanics feels weird and very off from other bosses, how would people know rage goes 50% -> 100% -> 175% -> 200% while almost every rages go 100% -> 200%. And even then, can't use 50% rage while at 175%.

As for each rage ideas:
- Bombinomicon sounds better to go for actual merasmus style, many bombs automatically appears at every directions, and 50% sounds way too little for this.
- Either reverse shove or flares can be a passive cooldown ability rather than shoving every abilities into rage, just depends which one fits better for it.

**Comment by FortyTwoFortyTwo** [comment]
Boss added and enabled weeks ago
