### ISSUE TITLE
Gamemode noticeably lags when too many bosses/minions/zombies are alive at once

### ISSUE THREAD

**Issue by woisalreadytaken** [redsunservers/VSH-Rewrite#344]
Making an issue so it isn't forgotten. It wasn't always like this, but I wouldn't be able to tell when it started happening. This is easy to reproduce in normal play with multiple battalion soldiers or seeldier rages.

Doesn't seem to matter if the boss is complex and checks stuff every frame (such as multiple pyrocars, though I'd assume it'd add a bit to the lag) or is as simple as a boss could be (such as seeldier minions).

**Comment by FortyTwoFortyTwo** [comment]
I'm pretty sure the reason behind this is too many functions being called at once, regardless if boss have any complex functions.
There are 4 functions being called every frame: `OnThink`, `OnButton`, `GetHudText` and `GetHudColor`. `GetHudText` and `GetHudColor` was recently added 4 months ago in #286, and CPU usage is very noticeably more used during during round active instead of setup time, because both function was not called during it.

`GetHudText` and `GetHudColor` can be merged into one function and not needing to get datas every frame, or only update when necessary. For `OnButton`, it might be possible to remove it and reuse one of the other `OnButtonX` functions instead.
